export const clientsBase = [
  'Rodriques e Lmeida',
  'D.D.A',
  'JPO',
  'Silvestre e Sousa',
  'FVL',
  'Ribeiro e Rocha',
  'Francometal',
  'Cliente1',
  'Cliente2',
  'Cliente3',
  'Cliente4',
  'Cliente5',
  'Cliente6',
  'Cliente7',
  'Cliente8',
  'Cliente9',
  'Cliente10',
];
